### ISSUE TITLE
api charset negotiation

### ISSUE THREAD

**Issue by 2e0byo** [OfficiumDivinum/OfficiumDivinum#2]
Currently @kormose it appears to give me utf-8 whatever I tell it.  I suspect (guess) that safari is still defaulting to latin-1 or something.  However, should we support encoding negotiation?

```
curl 2>/dev/null -X GET "https://2e0byo.co.uk/api/v1/martyrology/date/2021-02-26?version=1960" -H  "Accept-Charset: 8859-1" > /tmp/test && file -i /tmp/test
/tmp/test: application/json; charset=utf-8
```

**Comment by klsrqm** [comment]
I think it ought to be UTF8-only, transcoding is always a nightmare, and I see no real reason to implement it other than it being a nice feature to have.

**Comment by 2e0byo** [comment]
right.  On the basis that I _think_ the server is supplying UTF-8 (I'm
unable to reproduce display errors, so I assume it's a problem with
safari misinterpreting UTF-8, probably because we're not sending the
right headers), I'm going to close this.  So long as the frontend sees
UTF-8 it likely won't matter anyhow.
