### ISSUE TITLE
API support JSON requests as well as querystring?

### ISSUE THREAD

**Issue by 2e0byo** [OfficiumDivinum/OfficiumDivinum#7]
Currently the docs state that we support requests either as querystrings or as json requests (i.e. json in the body).  This was largely to allow getting lots of verses from the `/bible` endpoint.  Question: is this worth supporting a. universally, b. on some endpoints or c. not at all?

At the time I didn't know that you can just pass a query twice and then get in the application with `request.getlist("query")`.  I still think JSON is neater if you want to request fifty arbitrary verses or something like that, but I'm not sure it's worth it for this application.  Plus I think the bible endpoint is liable to be used to get *ranges* rather than individual verses anyhow.  (And readings in the office will likely be stored individually).

This boils down to: do you plan on writing any code in JS or something like that where it would be easier to format a *query* as JSON?

**Comment by kormose** [comment]
What I can see as a benefit to JSON queries (or rather, passing a set of objects as arguments) is potentially making background custom calls easier. I have been racking my brain over how Commons are best implemented — both in Breviary and Missal it's often "Everything from Common X except this collect"; or sometimes there are feasts where the half of the readings are from this common while the psalms are from another, etc. Depending on how the engine works it may make sense to have some sort of support where you can make calls like that in the background?

Another use it may have is if we ever implement a translation back-end where we may be posting arbitrary numbers of things back as JSON objects.

But when it comes to retrieving information I don't really see what (beyond a Bible browser) usage scenarios there may be.

**Comment by 2e0byo** [comment]
> What I can see as a benefit to JSON queries (or rather, passing a set
> of objects as arguments) is potentially making background custom calls
> easier.

That makes sense.  However, I can’t see any instances where one would
want to do that.

> I have been racking my brain over how Commons are best implemented —
> both in Breviary and Missal it's often "Everything from Common X
> except this collect"; or sometimes there are feasts where the half of
> the readings are from this common while the psalms are from another,
> etc. Depending on how the engine works it may make sense to have some
> sort of support where you can make calls like that in the background?

The way I see this there’s no reason to expose it to the application.  I
don’t see why the application would need to distinguish between
‘everything from common X bar this’ and ‘everything is proper’.  It just
cares about ‘display this’.

This is also a good point: I know how I want to do it, but it might not
be the best way.  I’ll open an issue on the mockups repo to provide a
mockup of how I think it should work.

I can think of one exception to this---if you actually wanted to expose
some kind of breviary-building api, so you could request a bunch of
offices and then build a booklet which said ‘everything from pp. 13--8
except this collect’.  That’s an interesting idea, but I’ve a hunch that
it would never work in practice without a lot of manual tweaking.

> Another use it may have is if we ever implement a translation back-end
> where we may be posting arbitrary numbers of things back as JSON
> objects.

You mean an API where I submit a string (or reference) and it yields me
the string in another language?  That’s an interesting idea, but quite a
long way from the way I concieve translation happening at the moment.

(In the current scheme, if you wanted to get something you would have to
do it by context: you can get any part of an object from the api, so
you’d have to get say
`office/?office=prime&part=hymn&part=psalms&lang=latin` and then repeat
the query with `&lang=french`, or pass `&trans=french` to get two at
once. But there’s no way of looking up an object just by sending it and
asking for another language.)

> But when it comes to retrieving information I don't really see what
> (beyond a Bible browser) usage scenarios there may be.

Right, I’ll park this issue and remove it from the docs.  We can always
add it at a later date.

For the Bible browser I think you just want ranges---how often do you
need to look up something like ‘the fifth verse in every 7th chapter’?
But maybe I should make it handle multiple ranges at once.
